### ISSUE TITLE
cron-start script wrong regexp

### ISSUE THREAD

**Issue by Zaitsev** [renskiy/cron-docker-image#1]
start-cron
Error in sed - if it as is its remove AAA_BB_CC  if exists AAA_BB
`sed --in-place "/^${VAR}/d" /etc/security/pam_env.conf || true`
should be 
`/^${VAR}\s/d` = **\s** is importat

**Comment by renskiy** [comment]
Thank you. But actually there is also '=' can be used. So the final command should look like this:

```
sed --in-place "/^${VAR}[[:blank:]=]/d" /etc/security/pam_env.conf || true
```
