### ISSUE TITLE
Use docker configs

### ISSUE THREAD

**Issue by grikdotnet** [renskiy/cron-docker-image#4]
Hi!
I'd prefer writing an email, but couldn't fine one.
I read your article at habr. Nice job, thank you for this solution.

This is a feature proposal - to use docker configs to set up cron tasks.
https://docs.docker.com/engine/swarm/configs/

What do you think about it?

Writing in English just in case, feel free to write in Russian, if it's more convenient for you.
Grigori

**Comment by grikdotnet** [comment]
Btw, you have `COPY crontabs /etc/crontabs` in readme, while the file is named `start-cron`.

**Comment by renskiy** [comment]
Hi Grigori! You're welcome.

About this feature, I think it is possible to use service configs without any changes of current `Dockerfile`. For example you can create service config with custom `--target` option which points to your cron config inside the container. In other words you can use service config as a container volume replacement.

About `COPY crontabs /etc/crontabs`, there are no errors. This row is optional and can be used to build images with built-in cron configs. Alternatively you can pass cron configs to the `start-cron` as described in README.

**Comment by grikdotnet** [comment]
thanks for explanation,
probably you mean `--config src=my_config,target=/path` :)

**Comment by renskiy** [comment]
Yes, service may be configured like you say. I was talking about `service config create`.
